---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: jekyll/jekyll:latest
  commands:
  - touch Gemfile.lock
  - chmod a+w Gemfile.lock
  - chown -R jekyll:jekyll /drone
  - gem update --system
  - gem install bundler
  - bundle install
  - bundle exec jekyll build

- name: publish
  image: appleboy/drone-scp
  settings:
    rm: true
    host:
      from_secret: scp_hosts
    key:
      from_secret: pipeline_key
    source: /drone/src/_site/
    target:
      from_secret: host_target
    username:
      from_secret: pipeline_user
    strip_components: 3
  when:
    branch:
      - master
    event:
      - push
