pipeline:
  jekyll-build:
    image: jekyll/jekyll:latest
    commands:
      - touch Gemfile.lock
      - chmod a+w Gemfile.lock
      - chown -R jekyll:jekyll /drone
      - gem update --system
      - gem install bundler
      - bundle install
      - bundle exec jekyll build
  transfer-build:
    image: drillster/drone-rsync
    hosts: ["hill", "theater", "lincoln"]
    key:
      from_secret: pipeline_key
    user:
      from_secret: pipeline_user
    source: ./*
    target:
      from_secret: host_target
    recursive: true
    delete: true
    when:
      branch: [master]
      event: [push]
