---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: jekyll/jekyll:latest
  commands:
  - touch Gemfile.lock
  - chmod a+w Gemfile.lock
  - chown -R jekyll:jekyll /drone
  - gem update --system
  - gem install bundler
  - bundle install
  - bundle exec jekyll build

- name: publish
  image: drillster/drone-rsync
  settings:
    delete: true
    hosts:
      from_secret: hosts
    key:
      from_secret: pipeline_key
    recursive: true
    source: /drone/src/_site/.
    target:
      from_secret: host_target
    user:
      from_secret: pipeline_user
    when:
      branch:
      - master
      event:
      - push
