---
kind: pipeline
type: docker
name: default

steps:

- name: build
  image: jekyll/jekyll:latest
  commands:
  - touch Gemfile.lock
  - chmod a+w Gemfile.lock
  - chown -R jekyll:jekyll /drone
  - gem update --system
  - gem install bundler
  - bundle install
  - bundle exec jekyll build

- name: publish
  image: drillster/drone-rsync
  settings:
    hosts:
      from_secret: hosts
    key:
      from_secret: pipeline_key
    user:
      from_secret: pipeline_user
    source: ./*
    target:
      from_secret: host_target
    recursive: true
    delete: true
    when:
      branch: [master]
      event: [push]
