# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

remote_theme: b2a3e8/jekyll-theme-console

header_pages:
  - index.md
  - about.md
  - contact.md


lsi: false
safe: true
source: [/]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge


style: dark # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

footer: 'GnuPG Key: A54D8FB506C103352E67737587CB975CFF2E7D8F'

google_analytics: UA-118294122-1

plugins:
  - jekyll-seo-tag

#SEO Customization
title: Anthony Rabbito
tagline: Anthony Rabbito's personal website & blog.
url: https://anthonyrabbito.com
social:
  name: Anthony Rabbito
  links:
    - https://github.com/anthr76
    - https://www.linkedin.com/in/anthony-rabbito-0a4448109/
